package com.tradesettlement.kafka;

public enum TradeEventType {
    TRADE_ACCEPTED,
    VALIDATION_COMPLETED,
    VALIDATION_REJECTED,
    ENRICHMENT_COMPLETED,
    ENRICHMENT_FAILED,
    ELIGIBILITY_CONFIRMED,
    ELIGIBILITY_REJECTED,
    SETTLEMENT_REQUESTED,
    SETTLEMENT_COMPLETED,
    SETTLEMENT_FAILED,
    STATUS_CHANGED
}
