spring:
  application:
    name: trade-settlement-backend
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: settlement
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    default-schema: settlement
    schemas: settlement
    locations: classpath:db/migration
  kafka:
    consumer:
      group-id: trade-settlement-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
